### ISSUE TITLE
[FEATURE] Add support for git metadata

### ISSUE THREAD

**Issue by kaiehrhardt** [terramate-io/terramate#1005]
**Is your feature request related to a problem? Please describe.**

I would like to use git metadata in my globals.

**Describe the solution you'd like**

Add `terramate.git.*` metadata variables. 
E.g.
- `terramate.git.branch`
- `terramate.git.rev`

**Comment by soerenmartius** [comment]
Hi @kaiehrhardt,

Thanks for reaching out and for your suggestion. Let me discuss this with the team before I get back to you in detail. I'll follow up shortly.

Thanks,
Soren

**Comment by kaiehrhardt** [comment]
Hey @soerenmartius,

any news here?

BR Kai :)

**Comment by soerenmartius** [comment]
Hi @kaiehrhardt,

Sorry for not getting back to you earlier. We discussed this internally we'd love to learn about your use case and what problem you are trying to solve? Please note that if you reference those in the code-generation, it will be triggered every time you switch branches.

**Comment by kaiehrhardt** [comment]
Hey @soerenmartius,

i would like to build something like review environments based on feature branches.

**Comment by mariux** [comment]
Would it be sufficient to support it at run-time or do you need the git meta data at code generation time? run time would be possible as this will not lead to generated code to be out of date depending on the branch.

**Comment by mariux** [comment]
> Would it be sufficient to support it at run-time or do you need the git meta data at code generation time? run time would be possible as this will not lead to generated code to be out of date depending on the branch.

@kaiehrhardt would you need this at run-time (`terramate run`) or at build-time (`terramate generate`)?

**Comment by kaiehrhardt** [comment]
@mariux Both would be nice. I'm not sure, if it breaks your design.

**Comment by k-eugen** [comment]
Hi

I think that I need this too.
I'm trying to use environments and branches in GitLab and script like this in plan and apply jobs
```yaml
  script:
    - terramate fmt --check
    # Filter stacks by environments
    - CHANGED_STACKS=$(terramate list --changed --tags terraform:$CI_ENVIRONMENT_TIER)
    - CHANGED_STACKS_NUMBER=$(echo $CHANGED_STACKS |wc -w)
    - if [ $CHANGED_STACKS_NUMBER -eq 0 ]; then echo "No changed terraform stacks in $CI_ENVIRONMENT_TIER environment tier. Nothing to do..."; exit 0; else echo -e "Changed stacks:\n$CHANGED_STACKS"; fi
    - !reference [.auth, script]
    - terramate run --parallel 1 --changed --tags terraform:$CI_ENVIRONMENT_TIER -- sh -c '
      git config --global credential.helper "store --file /tmp/secrets/.git-credentials" && 
      terraform init -lock-timeout=5m ; 
      git config --global --unset credential.helper'
    # Set "--disable-safeguards=git-untracked" after TF modules downloading
    - terramate run --disable-safeguards=git-untracked --parallel 5 --changed --tags terraform:$CI_ENVIRONMENT_TIER -- terraform validate
    - terramate run --disable-safeguards=git-untracked --changed --tags terraform:$CI_ENVIRONMENT_TIER -- terraform plan -lock-timeout=5m -out=out.tfplan
    - terramate run --disable-safeguards=git-untracked --changed --tags terraform:$CI_ENVIRONMENT_TIER -- terraform apply -input=false -auto-approve -lock-timeout=5m out.tfplan
    - terramate run --disable-safeguards=git-untracked --changed --tags terraform:$CI_ENVIRONMENT_TIER -- terraform plan -out drift.tfplan -detailed-exitcode
```

GitLab MR in development branch is not working
```sh
$ git branch
  development
* development_feature-test
  main
$ git rev-parse origin/development
9c3f914e472795e9ff425b1be90c17fabec046fd
$ terramate list --changed -B origin/development --tags terraform 
stacks/terraform/development/vpc
stacks/terraform/production/vpc
$ terramate list --changed -B 9c3f914e472795e9ff425b1be90c17fabec046fd --tags terraform 
stacks/terraform/development/vpc
stacks/terraform/production/vpc
$ terramate run --parallel 1 --changed -B origin/development --tags terraform -- echo $terramate.stack.name
Error: unable to reach remote default branch
> current HEAD is out-of-date with the remote base branch: Please update the current branch with the latest changes from the default branch.
$ terramate run --parallel 1 --changed -B 9c3f914e472795e9ff425b1be90c17fabec046fd --tags terraform -- echo $terramate.stack.name
Error: unable to reach remote default branch
> current HEAD is out-of-date with the remote base branch: Please update the current branch with the latest changes from the default branch.
```

**Comment by i4ki** [comment]
hey @k-eugen 

you need to configure gitlab to clone the repo and pull the history to use the change detection. Example:
```
variables:
  GIT_STRATEGY: clone  # clone entire repo instead of using fetch
  GIT_DEPTH: 0  # avoid shallow clone to give terramate all the info it needs
```
you did that?

**Comment by i4ki** [comment]
actually the "git strategy" can be "fetch", the important part is the `GIT_DEPTH: 0`.

alternative you can change this in the `settings -> CI/CD`, expand "General pipelines" and change the "GIT shallow clone" to zero (pull all commits).

**Comment by k-eugen** [comment]
Yes, I take as base pipeline from docs [https://terramate.io/docs/cli/automation/gitlab-ci/](https://terramate.io/docs/cli/automation/gitlab-ci/)
Fragments from my full pipeline
```yaml
terraform:plan:
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  extends:
  - ".common"
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: plan
  cache: []
  dependencies: []
  before_script:
  - - |
      mkdir -p /tmp/secrets && \
      chmod go-rwx /tmp/secrets && \
      echo "https://READ_TF_MODULES_TOKEN:${READ_TF_MODULES_TOKEN}@gitlab.domain.com" > /tmp/secrets/.git-credentials
    - git config --global --add safe.directory '*'
  script:
  - terramate fmt --check
  - export CHANGED_STACKS=$(terramate list --changed --tags terraform)
  - export CHANGED_STACKS_NUMBER=$(echo $CHANGED_STACKS |wc -w)
  - if [ $CHANGED_STACKS_NUMBER -eq 0 ]; then echo "No changed terraform stacks. Exiting.";
  ...

terraform:apply:development:
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  extends:
  - ".terraform:apply"
  stage: apply
  cache: []
  dependencies: []
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      == "$CI_ENVIRONMENT_TIER" && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED
  before_script:
  - - |
      mkdir -p /tmp/secrets && \
      chmod go-rwx /tmp/secrets && \
      echo "https://READ_TF_MODULES_TOKEN:${READ_TF_MODULES_TOKEN}@gitlab.domain.com" > /tmp/secrets/.git-credentials
    - git config --global --add safe.directory '*'
  script:
  - terramate fmt --check
  - CHANGED_STACKS=$(terramate list --changed --tags terraform:$CI_ENVIRONMENT_TIER)
  - CHANGED_STACKS_NUMBER=$(echo $CHANGED_STACKS |wc -w)
  - if [ $CHANGED_STACKS_NUMBER -eq 0 ]; then echo "No changed terraform stacks in
    $CI_ENVIRONMENT_TIER environment tier. Nothing to do..."; exit 0; else echo -e
    "Changed stacks:\n$CHANGED_STACKS"; fi
  ...
```

For sure I set "Git strategy" to "git clone" and "Git shallow clone" to 0 in GitLab UI in project settings.

Jobs succeded only after I changed terramate.config.git.default_branch from "main" to "development" in terramate project settings
```terramate
terramate {
  required_version = ">= 0.9.0"
  # required_version_allow_prereleases = true
  config {
    git {
      default_remote = "origin"
      # default_branch = "main"
      default_branch = "development"
    }
  }
}
```
