### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by g13013** [terramate-io/terramate#1353]
**Is your feature request related to a problem? Please describe.**
Add the ability to run against a stack by `name` or `id`

**Describe the solution you'd like**
In a CI in our testing scenario, we are deploying the stable version first before deploying the new change, simulating an upgrade to the platform before production. the problem is, if the stack gets moved in the filesystem in the head version, even if terramate detects the changed stack in the new version, I could not know what is the corresponding location of the stack in the stable version, combined with https://github.com/terramate-io/terramate/issues/723 one could do

```yaml
  prepare_contaxt:
    name: Context
    runs-on: ubuntu-latest
    outputs:
      changed_stacks=${{steps.get_stacks.outputs.stacks}}
    steps:
      - id: get_stacks
        run: echo "stacks=$(terramate list --changed --json)" > $GITHUB_OUTPUT
  test_deploy:
    name: Deploy / Test
    runs-on: ubuntu-latest
    environment: Staging
    needs: prepare_context
    strategy:
      matrix:
        stack: ${{ fromJson(needs.prepare_context.outputs.changed_stacks) }}
   steps:
    # ...
    - name: deploy stable
      run: |
        terramate list --changed | grep ${{ stack.id }} && # run only if it exist in stable
        terramate run -id ${{ stack.id }} -- terraform apply
```

**Describe alternatives you've considered**

**Additional context**
